name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the docker image
        run: |
          docker login -u edzhu -p ${{ secrets.DOCKER_PASSWORD }}
          docker build . --file Dockerfile --tag edzhu/redis:latest --tag edzhu/redis:${{ github.run_number }}
          docker push -a edzhu/redis
